version: "3.5"
networks:
  default:
    external:
      name: gateway
  mongodb:
    driver: bridge
    internal: true

services:
  mongodb:
    image: "mongo:3"
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - "${DATA_DIR}/samplist/mongodb:/data/db"
    networks:
      - mongodb

  api:
    image: "southclaws/samp-servers-api:latest"
    restart: on-failure
    environment:
      SAMPLIST_BIND: "0.0.0.0:80"
      SAMPLIST_MONGO_USER: "${MONGODB_USERNAME}"
      SAMPLIST_MONGO_PASS: "${MONGODB_PASSWORD}"
      SAMPLIST_MONGO_HOST: mongodb
      SAMPLIST_MONGO_PORT: "27017"
      SAMPLIST_MONGO_NAME: admin
      SAMPLIST_MONGO_COLLECTION: servers
      SAMPLIST_QUERY_INTERVAL: "120s"
      SAMPLIST_MAX_FAILED_QUERY: "10"
      SAMPLIST_VERIFY_BY_HOST: "true"
      SAMPLIST_LEGACY_LIST: "true"
    networks:
      - default
      - mongodb
    depends_on:
      - mongodb
    labels:
      traefik.enable: true
      traefik.docker.network: gateway
      traefik.http.routers.samplist_api.rule: Host(`api.samp-servers.net`)
      traefik.http.routers.samplist_api.entrypoints: https
      traefik.http.routers.samplist_api.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: true

  prometheus:
    image: "prom/prometheus"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=10GB
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    restart: always
    volumes:
      - ${DATA_DIR}/samplist/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default
    labels:
      traefik.enable: true
      traefik.docker.network: gateway
      traefik.http.routers.samplist_prom.rule: Host(`data.samp-servers.net`)
      traefik.http.routers.samplist_prom.entrypoints: https
      traefik.http.routers.samplist_prom.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: true
