global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: samp-servers-api
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - "samp-servers-api"
        type: "A"
        port: 80
